"""add room_id to messages

Revision ID: 27a2e5d6bffd
Revises: ee24520e4b9e
Create Date: 2026-01-20 21:26:53.899317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a2e5d6bffd'
down_revision = 'ee24520e4b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_messages_room_id_rooms', 'rooms', ['room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_room_id_rooms', type_='foreignkey')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###
