"""Add AIModel table

Revision ID: 52b3ab138780
Revises: e5e3cbe490de
Create Date: 2026-01-20 19:41:06.929035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b3ab138780'
down_revision = 'e5e3cbe490de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('is_enabled', sa.Boolean(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('api_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('api_key',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_ai_models_name'))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai_models_name'), ['name'], unique=1)
        batch_op.alter_column('api_key',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('api_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('is_enabled')
        batch_op.drop_column('model_name')

    # ### end Alembic commands ###
