"""add avatar field

Revision ID: 54abf0f61ce3
Revises: 148208bd6285
Create Date: 2026-01-21 11:22:48.973631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54abf0f61ce3'
down_revision = '148208bd6285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
