"""Add creator to Room

Revision ID: 5ac1c266748d
Revises: 8f9b75e31fb9
Create Date: 2026-01-20 17:39:17.545347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac1c266748d'
down_revision = '8f9b75e31fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_rooms_creator_id_users', 'users', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rooms_creator_id_users', type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
