"""Add nickname and avatar to AdminUser

Revision ID: d0bf4d31e073
Revises: 273d7a1ccd18
Create Date: 2026-01-20 16:41:08.237903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bf4d31e073'
down_revision = '273d7a1ccd18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_column('avatar')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
