"""Add WSServer

Revision ID: e5e3cbe490de
Revises: 5ac1c266748d
Create Date: 2026-01-20 19:17:27.422582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e3cbe490de'
down_revision = '5ac1c266748d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ws_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ws_servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ws_servers_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ws_servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ws_servers_name'))

    op.drop_table('ws_servers')
    # ### end Alembic commands ###
